name: Convert Direct.txt to JSON

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read Direct.txt and convert to JSON
        run: |
          input_file="Direct.txt"
          output_file="output.json"

          echo '{
            "version": 1,
            "rules": [
              {
                "domain": [],
                "domain_suffix": []
              }
            ]
          }' > $output_file

          while IFS=, read -r type value; do
            value=$(echo "$value" | tr -d '\r')  # 去掉 \r 字符
            if [[ "$type" == "DOMAIN" ]]; then
              jq --arg value "$value" '.rules[0].domain += [$value]' $output_file > tmp.json && mv tmp.json $output_file
            elif [[ "$type" == "DOMAIN-SUFFIX" ]]; then
              jq --arg value "$value" '.rules[0].domain_suffix += [$value]' $output_file > tmp.json && mv tmp.json $output_file
            fi
          done < <(tr -d '\r' < "$input_file")

          cat $output_file

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b update-direct-json
          git add output.json
          if ! git diff --cached --quiet; then
            git commit -m "Convert Direct.txt to JSON format"
            git pull origin update-direct-json || true  # 尝试拉取远程更改
            git push origin update-direct-json
          else
            echo "No changes to commit."
          fi
