name: Convert Text Files to JSON

on:
  push:
    branches:
      - main  # 觸發工作流的分支，可以根據需要修改
    paths:
      - '*.txt'  # 只在根目錄下的 .txt 文件發生變更時觸發

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert Text to JSON
        run: |
          convert_to_json() {
            input_file="$1"
            output_file="$2"

            # 創建 JSON 結構
            echo '{
              "version": 1,
              "rules": [
                {
                  "ip_cidr": [],
                  "domain": [],
                  "domain_suffix": [],
                  "domain_keyword": []
                }
              ]
            }' > "$output_file"

            # 讀取文件內容並填充 JSON
            while IFS= read -r line; do
              # 刪除行末的 \r 字符
              line=$(echo "$line" | tr -d '\r')
              if [[ $line == IP-CIDR,* ]]; then
                ip_cidr=$(echo "$line" | cut -d',' -f2)
                jq --arg ip_cidr "$ip_cidr" '.rules[0].ip_cidr += [$ip_cidr]' "$output_file" > tmp.json && mv tmp.json "$output_file"
              elif [[ $line == DOMAIN,* ]]; then
                domain=$(echo "$line" | cut -d',' -f2)
                jq --arg domain "$domain" '.rules[0].domain += [$domain]' "$output_file" > tmp.json && mv tmp.json "$output_file"
              elif [[ $line == DOMAIN-SUFFIX,* ]]; then
                domain_suffix=$(echo "$line" | cut -d',' -f2)
                jq --arg domain_suffix "$domain_suffix" '.rules[0].domain_suffix += [$domain_suffix]' "$output_file" > tmp.json && mv tmp.json "$output_file"
              elif [[ $line == DOMAIN-KEYWORD,* ]]; then
                domain_keyword=$(echo "$line" | cut -d',' -f2)
                jq --arg domain_keyword "$domain_keyword" '.rules[0].domain_keyword += [$domain_keyword]' "$output_file" > tmp.json && mv tmp.json "$output_file"
              fi
            done < "$input_file"

            # 刪除空的數組
            jq 'del(.rules[0].ip_cidr | select(length == 0)) | del(.rules[0].domain | select(length == 0)) | del(.rules[0].domain_suffix | select(length == 0)) | del(.rules[0].domain_keyword | select(length == 0))' "$output_file" > tmp.json && mv tmp.json "$output_file"
          }

          # 遍歷根目錄下的所有 .txt 文件並生成相應的 .json 文件
          for txt_file in *.txt; do
            if [ -f "$txt_file" ]; then  # 確保是文件
              # 獲取文件名（不帶擴展名）
              base_name=$(basename "$txt_file" .txt)
              output_file="Config/Sing_box/Rule_set/${base_name}.json"
              convert_to_json "$txt_file" "$output_file"
            fi
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull --rebase origin main  # 使用 rebase 拉取遠端的更改
          git add Config/Sing_box/Rule_set/*.json
          git commit -m "Update JSON files from .txt files" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
