name: Update Greylist

on:
  workflow_dispatch:  # 允許手動觸發
  push:
    branches:
      - main  # 你可以根据需要修改为其他分支
    paths:
      - Proxy.txt
      - Videos.txt

jobs:
  update-greylist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Process Proxy.txt and Videos.txt
        run: |
          # 创建一个临时文件
          temp_file="Mosdns/Greylist_temp.txt"

          # 复制原始 Greylist.txt 的内容到临时文件
          # 保留 #Remote 及其以上的内容
          awk '/#Remote/{print; exit} {print}' Mosdns/Greylist.txt > $temp_file

          # 添加 #Proxy 标记
          echo "#Proxy" >> $temp_file
          while IFS= read -r line; do
            if [[ ! $line =~ ^# ]]; then
              if [[ $line == DOMAIN,* ]]; then
                echo "full:${line#DOMAIN,}" >> $temp_file
              elif [[ $line == DOMAIN-SUFFIX,* ]]; then
                echo "domain:${line#DOMAIN-SUFFIX,}" >> $temp_file
              elif [[ $line == DOMAIN-KEYWORD,* ]]; then
                echo "keyword:${line#DOMAIN-KEYWORD,}" >> $temp_file
              fi
            fi
          done < Proxy.txt

          # 将结果写入 Mosdns/Greylist.txt，如果統一文件的話代碼就放到下面
          mv $temp_file Mosdns/Greylist.txt

          # 复制原始 Streaming.txt 的内容到临时文件
          # 保留 #Remote 及其以上的内容 統一的話代碼刪除或注釋
          awk '/#Remote/{print; exit} {print}' Mosdns/Streaming.txt > $temp_file
          
          # 添加 #Videos 标记
          echo "#Videos" >> $temp_file
          while IFS= read -r line; do
            if [[ ! $line =~ ^# ]]; then
              if [[ $line == DOMAIN,* ]]; then
                echo "full:${line#DOMAIN,}" >> $temp_file
              elif [[ $line == DOMAIN-SUFFIX,* ]]; then
                echo "domain:${line#DOMAIN-SUFFIX,}" >> $temp_file
              elif [[ $line == DOMAIN-KEYWORD,* ]]; then
                echo "keyword:${line#DOMAIN-KEYWORD,}" >> $temp_file
              fi
            fi
          done < Videos.txt

          # 将结果写入 Mosdns/Streaming.txt
          mv $temp_file Mosdns/Streaming.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Mosdns/Greylist.txt
          git add Mosdns/Streaming.txt
          git commit -m "Update Greylist.txt"
          git push
