name: Update Direct.txt

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download content
        run: |
          curl -o new_content.txt https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/cn.list

      - name: Check if Direct.txt needs to be updated
        run: |
          if ! cmp -s new_content.txt Direct.txt; then
            echo "Files are different, updating Direct.txt"
            cat new_content.txt >> Direct.txt
            echo "true" >> $GITHUB_ENV  # 设置环境变量以指示有更改
          else
            echo "No changes detected in Direct.txt"
            echo "false" >> $GITHUB_ENV  # 设置环境变量以指示没有更改
          fi
          rm new_content.txt  # 清理临时文件

      - name: Commit changes
        if: env.changes == 'true'  # 只有在有更改时才执行
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          git add Direct.txt
          git commit -m "Update Direct.txt with new content from cn.list"
          git push
