name: Update Direct.txt

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and format content
        run: |
          curl -s https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.list | \
          awk '{if ($0 ~ /:/) print "IP-CIDR6," $0 ",no-resolve"; else print "IP-CIDR," $0 ",no-resolve"}' > new_entries.txt

      - name: Update Direct.txt
        run: |
          awk '/#CN/{print; found=1; next} found{exit} {print}' Direct.txt > temp.txt
          cat new_entries.txt >> temp.txt
          mv temp.txt Direct.txt

      - name: Commit changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add Direct.txt
          git commit -m "Update Direct.txt with new entries from cn.list" || echo "No changes to commit"
          git push
